//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCompany_1_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin:User
    {
        public int idAdmin { get; set; }
        public Nullable<int> experience { get; set; }
        public Nullable<int> salary { get; set; }

        public static admin Convert(User v)
        {
            admin adm = new admin();
            adm.login = v.login;
            adm.password = v.password;
            adm.surname = v.surname;
            adm.name = v.name;
            if (v.patronymic != null)
            {
                adm.patronymic = v.patronymic;
            }
            adm.phoneNumber = v.phoneNumber;
            adm.workerCode = v.workerCode;
            return adm;
        }
    }
    
}
