//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCompany_1_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_selected
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bus_selected()
        {
            this.ticket = new HashSet<ticket>();
        }
    
        public int idBus_selected { get; set; }
        public int idRoute { get; set; }
        public int idBus { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int idFirstDriver { get; set; }
        public Nullable<int> idSecondDriver { get; set; }
        public Nullable<int> idConductor { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual driver driver { get; set; }
        public virtual driver driver1 { get; set; }
        public virtual driver driver2 { get; set; }
        public virtual route route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> ticket { get; set; }
    }
}
