//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCompany_1_1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class customer : User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.order = new HashSet<order>();
            this.ticket = new HashSet<ticket>();
        }

        public int idCustomer { get; set; }

        public static customer Convert(User v)
        {
            customer cus = new customer();
            cus.login = v.login;
            cus.password = v.password;
            cus.surname = v.surname;
            cus.name = v.name;
            if (v.patronymic != null)
            {
                cus.patronymic = v.patronymic;
            }
            cus.phoneNumber = v.phoneNumber;
            cus.workerCode = "";
            return cus;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> ticket { get; set; }
    }
}
