//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCompany_1_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dest_route
    {
        public int idDest_route { get; set; }
        public int idRoute { get; set; }
        public int idDestination { get; set; }
        public Nullable<System.TimeSpan> timeArrive { get; set; }
        public Nullable<System.TimeSpan> timeOut { get; set; }
    
        public virtual destination destination { get; set; }
    }
}
