//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCompany_1_1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class dispatcher : User
    {
        public int idDispatcher { get; set; }
        public Nullable<int> experience { get; set; }
        public Nullable<int> salary { get; set; }

        public static dispatcher Convert(User v)
        {
            dispatcher d = new dispatcher();
            d.login = v.login;
            d.password = v.password;
            d.surname = v.surname;
            d.name = v.name;
            if (v.patronymic != null)
            {
                d.patronymic = v.patronymic;
            }
            d.phoneNumber = v.phoneNumber;
            d.workerCode = v.workerCode;
            return d;
        }
    }
}
