//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCompany_1_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dispatcher:User
    {
        public int idDispatcher { get; set; }
        public Nullable<int> experience { get; set; }
        public Nullable<int> salary { get; set; }
        public static dispatcher Convert(User v)
        {
            var a = new dispatcher();
            a.login = v.login;
            a.password = v.password;
            a.name = v.name;
            a.surname = v.surname;
            a.patronymic = v.patronymic;
            a.phoneNumber = v.phoneNumber;
            a.workerCode = v.workerCode;
            return a;
        }


    }
}
