//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCompany_1_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_car_type
    {
        public int idService_car_type { get; set; }
        public int idService { get; set; }
        public int idCarType { get; set; }
    
        public virtual car_type car_type { get; set; }
        public virtual service service { get; set; }
    }
}
