//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCompany_1_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setupped_route
    {
        public int idSetupped_route { get; set; }
        public int idRoute { get; set; }
        public int idBus { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateEnd { get; set; }
        public int idFirstDriver { get; set; }
        public Nullable<int> idSecondDriver { get; set; }
        public Nullable<int> idConductor { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual driver firstDriver { get; set; }
        public virtual driver secondDriver { get; set; }
        public virtual driver conductor { get; set; }
        public virtual route route { get; set; }
    }
}
