/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

import static org.junit.Assert.*;

public class HelloTest {
    @Test
    public void testFileEquals() throws FileNotFoundException {
        File file = new File("src/main/resources/file.txt");
        Scanner sc = new Scanner(file);
        assertEquals("!!!",sc.next());
    }

    @Test(expected = FileNotFoundException.class)
    public void testFileNotFound() throws FileNotFoundException {
        File file = new File("src/test/resources/file.txt");
        Scanner sc = new Scanner(file);
    }
}
